name: Build WalletCore APK

on:
  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-22.04


    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"


    - name: Install Java 17
      run: |

        sudo apt update

        sudo apt install -y openjdk-17-jdk

        echo "JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64" >> $GITHUB_ENV

        java -version



    - name: Setup Android
      uses: android-actions/setup-android@v3



    - name: Accept licenses
      run: |

        yes | sdkmanager --licenses



    - name: Install SDK
      run: |

        sdkmanager \
        "platform-tools" \
        "platforms;android-35" \
        "build-tools;35.0.0" \
        "ndk;27.3.13750724"



    - name: Install build tools
      run: |

        pip install --upgrade pip

        pip install \
        buildozer==1.6.0 \
        cython==0.29.36 \
        python-for-android \
        appdirs



    - name: Clear cache
      run: |

        rm -rf ~/.buildozer

        rm -rf .buildozer



    - name: Build APK
      run: |

        buildozer android debug



    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:

        name: WalletCore APK

        path: bin/*.apk
