name: Build WalletCore APK

on:
  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-22.04


    steps:

    # ==========================
    # DOWNLOAD PROJECT
    # ==========================

    - name: Checkout
      uses: actions/checkout@v4



    # ==========================
    # PYTHON
    # ==========================

    - name: Setup Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"



    # ==========================
    # SYSTEM DEPENDENCIES
    # ==========================

    - name: Install dependencies
      run: |

        sudo apt update

        sudo apt install -y \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          cmake



    # ==========================
    # FORCE JAVA 17
    # ==========================

    - name: Configure Java 17
      run: |

        echo "JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64" >> $GITHUB_ENV

        echo "/usr/lib/jvm/temurin-17-jdk-amd64/bin" >> $GITHUB_PATH

        java -version



    # ==========================
    # ANDROID SDK
    # ==========================

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3



    # ==========================
    # ACCEPT LICENSES
    # ==========================

    - name: Accept Android licenses
      run: |

        yes | sdkmanager --licenses || true



    # ==========================
    # INSTALL ANDROID PACKAGES
    # ==========================

    - name: Install Android packages
      run: |

        sdkmanager \
          "platform-tools" \
          "platforms;android-35" \
          "build-tools;35.0.0" \
          "ndk;27.3.13750724"



    # ==========================
    # PYTHON BUILD TOOLS
    # ==========================

    - name: Install Buildozer
      run: |

        python -m pip install --upgrade pip

        pip install \
          buildozer==1.6.0 \
          cython==0.29.36 \
          python-for-android \
          appdirs \
          virtualenv



    # ==========================
    # CLEAN OLD CACHE
    # ==========================

    - name: Clean Buildozer
      run: |

        rm -rf .buildozer

        rm -rf bin



    # ==========================
    # BUILD APK
    # ==========================

    - name: Build WalletCore APK
      run: |

        buildozer android debug



    # ==========================
    # UPLOAD APK
    # ==========================

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:

        name: WalletCore-debug-apk

        path: bin/*.apk
