name: Build WalletCore APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            wget


      - name: Install Android SDK packages
        run: |
          yes | sdkmanager --licenses || true
          sdkmanager \
            "platform-tools" \
            "platforms;android-35" \
            "build-tools;35.0.0"


      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          python -m pip install buildozer cython==0.29.36


      - name: Configure Android paths
        run: |
          echo "ANDROIDSDK=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROIDAPI=35" >> $GITHUB_ENV
          echo "ANDROIDNDK=$ANDROID_HOME/ndk/25.2.9519653" >> $GITHUB_ENV


      - name: Build APK
        run: |
          buildozer android debug


      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: WalletCore-debug-apk
          path: bin/*.apk
