name: WalletCore APK

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          git zip unzip openjdk-11-jdk \
          python3-pip python3-setuptools \
          python3-wheel build-essential \
          libffi-dev libssl-dev


    - name: Install Python tools
      run: |
        python3 -m pip install --upgrade pip
        pip install Cython==0.29.37
        pip install sh==1.14.3
        pip install buildozer==1.5.0


    - name: Build APK
      env:
        ACCEPT_ANDROID_SDK_LICENSE: "yes"
      run: |
        rm -rf .buildozer
        rm -rf bin
        yes | buildozer android debug


    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: WalletCore-debug
        path: bin/*.apk
