name: WalletCore APK

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:

    - uses: actions/checkout@v4


    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          openjdk-17-jdk \
          zip unzip \
          autoconf automake libtool \
          pkg-config \
          zlib1g-dev \
          libffi-dev \
          libssl-dev


    - name: Install Python tools
      run: |
        python3 -m pip install --upgrade pip
        pip install cython==0.29.37
        pip install buildozer==1.5.0
        pip install python-for-android==2024.01.21

    - name: Build APK
      run: |
        rm -rf .buildozer
        rm -rf bin
        buildozer android debug


    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: WalletCore-debug
        path: bin/*.apk
