name: WalletCore APK

on:
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-22.04

    container:
      image: kivy/buildozer:latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Clean
      run: |
        rm -rf ~/.buildozer
        rm -rf .buildozer
        rm -rf bin

    - name: Install dependencies
      run: |
        pip install --upgrade "cython<3"


    - name: Environment
      run: |
        python3 --version
        pip --version
        cython --version
        buildozer --version
        java -version



    - name: Check project files
      run: |
        echo "FILES:"
        find . -maxdepth 3 -type f | sort
        echo "ICON:"
        ls -la assets/
        file assets/icon.png

    - name: Check requirements
      run: |
        echo "BUILD SPEC:"
        grep requirements buildozer.spec
        echo "REQ TXT:"
        cat requirements.txt


    - name: Build APK
      env:
        P4A_RELEASE_KEYSTORE: ""
      run: |
        yes | buildozer android debug


    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:

        name: WalletCore-debug

        path: bin/*.apk
