name: WalletCore APK

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    env:
      ANDROID_HOME: /usr/local/lib/android/sdk
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/25.2.9519653


    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Install system packages
      run: |
        sudo apt update
        sudo apt install -y \
          git \
          zip \
          unzip \
          openjdk-17-jdk


    - name: Setup Android licenses
      run: |

        mkdir -p ~/.android

        touch ~/.android/repositories.cfg

        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

        echo "SDK licenses accepted"


    - name: Install Android SDK packages
      run: |

        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
        "platform-tools" \
        "platforms;android-35" \
        "build-tools;35.0.0"


    - name: Check Android SDK
      run: |

        echo "ANDROID_HOME=$ANDROID_HOME"

        ls $ANDROID_HOME

        ls $ANDROID_HOME/build-tools

        ls $ANDROID_HOME/platforms


    - name: Check NDK #1
      run: |

        echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME"

        ls $ANDROID_NDK_HOME

        $ANDROID_NDK_HOME/ndk-build --version || true


    - name: Check NDK #2
      run: |

        echo "Available NDKs:"
        ls $ANDROID_HOME/ndk

        test -d $ANDROID_NDK_HOME && echo "NDK OK"


    - name: Install Python tools
      run: |

        python3 -m pip install --upgrade pip

        pip install buildozer==1.6.0

        pip install cython==0.29.36


    - name: Build WalletCore
      run: |

        buildozer --allow-root android clean

        buildozer --allow-root -v android debug


    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: WalletCore APK
        path: bin/*.apk
