name: WalletCore APK

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    env:
      ANDROID_HOME: /usr/local/lib/android/sdk
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/25.2.9519653
      JAVA_HOME: /usr/lib/jvm/temurin-17-jdk-amd64

    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          python3-pip \
          python3-setuptools \
          python3-wheel \
          openjdk-17-jdk \
          unzip \
          zip \
          git


    - name: Java
      run: |
        java -version
        javac -version


    - name: Android SDK setup
      run: |

        echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true


    - name: Install Android packages
      run: |

        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
        "platform-tools" \
        "platforms;android-35" \
        "build-tools;35.0.0" \
        "ndk;25.2.9519653"


    - name: Check Android
      run: |

        echo $ANDROID_NDK_HOME

        ls $ANDROID_HOME/build-tools

        ls $ANDROID_HOME/ndk


    - name: Install Buildozer
      run: |

        python3 -m pip install --upgrade pip

        pip install buildozer==1.6.0

        pip install cython==0.29.36


    - name: Clear cache
      run: |

        rm -rf ~/.buildozer
        rm -rf .buildozer
        rm -rf bin

    - name: Force Android build tools
      run: |
        echo "ANDROID_BUILD_TOOLS_VERSION=35.0.0" >> $GITHUB_ENV
        ls $ANDROID_HOME/build-tools

    - name: Build APK
      run: |

        buildozer -v android debug


    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:

        name: WalletCore-debug

        path: bin/*.apk
