name: Create Keystore

on:
  workflow_dispatch:

jobs:
  keystore:
    runs-on: ubuntu-latest

    steps:
    - name: Create keystore
      run: |
        keytool -genkeypair \
        -v \
        -keystore walletcore.keystore \
        -alias walletcore \
        -keyalg RSA \
        -keysize 2048 \
        -validity 10000 \
        -storepass WalletCore123! \
        -keypass WalletCore123! \
        -dname "CN=DEVELOP4WORLD, OU=Development, O=DEVELOP4WORLD, L=Pancevo, ST=Serbia, C=RS"

    - name: Check keystore
      run: |
        keytool -list -keystore walletcore.keystore -storepass WalletCore123!

    - name: Upload keystore
      uses: actions/upload-artifact@v4
      with:
        name: walletcore-keystore
        path: walletcore.keystore
