name: Create New WalletCore Keystore

on:
  workflow_dispatch:

jobs:
  keystore:
    runs-on: ubuntu-latest

    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:
      - name: Check keystore secrets
        run: |
          test -n "$KEYSTORE_PASSWORD"
          test -n "$KEY_PASSWORD"

      - name: Create keystore
        run: |
          keytool -genkeypair \
            -v \
            -keystore walletcore.keystore \
            -alias walletcore \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass "$KEYSTORE_PASSWORD" \
            -keypass "$KEY_PASSWORD" \
            -dname "CN=DEVELOP4WORLD, OU=Development, O=DEVELOP4WORLD, L=Pancevo, ST=Serbia, C=RS"

      - name: Check keystore
        run: |
          keytool -list \
            -keystore walletcore.keystore \
            -storepass "$KEYSTORE_PASSWORD" \
            -alias walletcore

      - name: Upload keystore
        uses: actions/upload-artifact@v4
        with:
          name: walletcore-keystore
          path: walletcore.keystore
